'''Script to take a numpy isGamma prediction file and a corresponding VERITAS real data file replace it's isGamma prediction with the one generated by a CNN. Written 3/7/2019 by S. Spencer'''


import sys
sys.argv.append('-b-')
import ROOT
import numpy as np
from root_numpy import tree2array, root2array,array2root,list_trees,list_branches,array2tree,array2root
from ROOT import gSystem, TFile, TTreeReader
import root_numpy
from rootpy.tree import Tree, TreeModel, FloatCol, IntCol
from rootpy.io import root_open
import os

#ROOT.ROOT.EnableImplicitMT()
#ROOT.gROOT.SetBatch(True)
if gSystem.Load("$EVNDISPSYS/lib/libVAnaSum.so"):
    print ("Problem with evndisp")

runfile='/lustre/fs19/group/cta/users/sspencer/ver/aux/64080anasum.root'
predfile='/lustre/fs19/group/cta/users/sspencer/predictions/64080_vtest1_predictions_REAL.npy'
evfile='/lustre/fs19/group/cta/users/sspencer/events/64080_vtest1_eventnos_REAL.npy'
outfile='/lustre/fs19/group/cta/users/sspencer/ver/aux/64080_DL.root'

os.system('rm '+outfile) #Delete any existing room files with output name, stops issues with rewriting root files

pred=np.load(predfile)
eventnumbers=np.load(evfile)
print(np.shape(pred),np.shape(eventnumbers))

rootfile = TFile(runfile,'read')
tdict={}
tlist=list_trees(runfile)
for k in tlist:
    tdict[k]=tree2array(rootfile.Get(k))
print(tdict.keys())

onregion=tdict['run_64080/stereo/data_on']
for x in np.arange(len(onregion)):
    evno=onregion[x][1]
    evloc=np.where(eventnumbers==evno)
    if evloc[0].size==0:
        np.delete(onregion,x)
        continue
    #Delete events for which there are no predictions
    onregion[x][-2]=np.argmax(pred[evloc])

offregion=tdict['run_64080/stereo/data_off']
for x in np.arange(len(offregion)):
    evno=offregion[x][1]
    evloc=np.where(eventnumbers==evno)
    if evloc[0].size==0:
        np.delete(offregion,x)
        continue
    offregion[x][-2]=np.argmax(pred[evloc])


rootfile.Close()

for k in tdict.keys():
    rooarr=array2root(tdict[k],outfile,treename=k,mode='update')
    #rooarr.Write()
    #rooarr.Delete()

#output.Write()
#output.Close()
